---
- hosts: localServers
  tasks:
    - name: Ping
      ping:
    - name: copy src.txt as dest.txt in the same dir
      copy:
        src: src.txt
        dest: /home/pi/test/dest.txt
      tags:
        - simple_copy