name: Install and run a Docker container
hosts: localhost
gather_facts: "no"
tasks:
  name: Install Dependencies
  action:
    module: apt
    args:
      name: "{{ item }}"
      update_cache: "yes"
      state: present
  with_items:
    - python-dev
    - python-setuptools
  register: "{{name_}}"
